<?php

namespace Geekish\FakerProviders\Arts;

use Faker\Provider\Base;

class Literature extends Base
{
    /** @var string[] */
    protected static array $authors = [
        'A.A. Milne',
        'Agatha Christie',
        'Alan Moore and Dave Gibbons',
        'Albert Camus',
        'Aldous Huxley',
        'Alexander Pope',
        'Alexandre Dumas',
        'Alice Walker',
        'Andrew Lang',
        'Anne Frank',
        'Anthony Burgess',
        'Anthony Trollope',
        'Antoine de Saint-Exupéry',
        'Anton Chekhov',
        'Anton Pavlovich Chekhov',
        'Arthur Conan Doyle',
        'Arthur Schopenhauer',
        'Aylmer Maude',
        'Ayn Rand',
        'Beatrix Potter',
        'Benjamin Disraeli',
        'Benjamin Jowett',
        'Bernard Shaw',
        'Bertrand Russell',
        'Bhagavanlal Indrajit',
        'Boris Pasternak',
        'Bram Stoker',
        'Brian Evenson',
        'C.E. Brock',
        'C.S. Lewis',
        'Carson McCallers',
        'Charles Dickens',
        'Charles E. Derbyshire',
        'Charlotte Brontë',
        'Charlotte Perkins Gilman',
        'Chinua Achebe',
        'Clifford R. Adams',
        'Constance Garnett',
        'Cormac McCarthy',
        'D.H. Lawrence',
        'Dan Brown',
        'Daniel Defoe',
        'Dante Alighieri',
        'Dashiell Hammett',
        'David Widger',
        'David Wyllie',
        'Dean Koontz',
        'Don DeLillo',
        'E.M. Forster',
        'Edgar Allan Poe',
        'Edgar Rice Burroughs',
        'Elizabeth Cleghorn Gaskell',
        'Elizabeth Von Arnim',
        'Emily Brontë',
        'Erich Remarque',
        'Ernest Hemingway',
        'Evelyn Waugh',
        'F. Scott Fitzgerald',
        'Ford Madox Ford',
        'Frances Hodgson Burnett',
        'Frank Herbert',
        'Frank T. Merrill',
        'Franz Kafka',
        'Friedrich Wilhelm Nietzsche',
        'Fyodor Dostoyevsky',
        'G.K. Chesterton',
        'Gabriel Garcia Marquez',
        'Geoffrey Chaucer',
        'George Eliot',
        'George Grossmith',
        'George Orwell',
        'George R. R. Martin',
        'George Saunders',
        'Grady Ward',
        'Graham Greene',
        'Gustave Doré',
        'Gustave Flaubert',
        'Guy de Maupassant',
        'Günter Grass',
        'H.G. Wells',
        'H.P. Lovecraft',
        'Harper Lee',
        'Harriet Beecher Stowe',
        'Haruki Murakami',
        'Henrik Ibsen',
        'Henry David Thoreau',
        'Henry Fielding',
        'Henry James',
        'Henry Miller',
        'Henry Morley',
        'Herman Melville',
        'Hermann Broch',
        'Homer',
        'Honoré de Balzac',
        'Ian McEwan',
        'Isabel Florence Hapgood',
        'Italo Calvino',
        'J.D. Salinger',
        'J.K. Rowling',
        'J.M. Barrie',
        'J.R.R. Tolkien',
        'Jack Kerouac',
        'Jack London',
        'Jacob Grimm',
        'Jacqueline Crooks',
        'James Baldwin',
        'James Dickey',
        'James Ellroy',
        'James Joyce',
        'James Patterson',
        'Jane Austen',
        'Johann Wolfgang von Goethe',
        'John Bunyan',
        'John Camden Hotten',
        'John Dos Passos',
        'John Green',
        'John Grisham',
        'John Kennedy Toole',
        'John Milton',
        'John Ormsby',
        'John Steinbeck',
        'John Updike',
        'Jonathan Franzen',
        'Jonathan Swift',
        'Joseph Conrad',
        'Joseph Heller',
        'José Rizal',
        'Judy Blume',
        'Jules Verne',
        'Junot Diaz',
        'Karl Marx',
        'Kazuo Ishiguro',
        'Ken Follett',
        'Ken Kesey',
        'Kenneth Grahame',
        'Khaled Hosseini',
        'Kingsley Amis',
        'Kurt Vonnegut',
        'L. Frank Baum',
        'L.M. Montgomery',
        'Laurence Sterne',
        'Leo Tolstoy',
        'Lewis Carroll',
        'Louisa May Alcott',
        'Louise Maude',
        'Malcolm Lowry',
        'Marcel Proust',
        'Margaret Atwood',
        'Margaret Mitchell',
        'Marilynne Robinson',
        'Mark Twain',
        'Martin Amis',
        'Mary Shelley',
        'Michael Chabon',
        'Miguel de Cervantes',
        'Mikhail Bulgakov',
        'Muriel Spark',
        'Nancy Mitford',
        'Nathanael West',
        'Nathaniel Hawthorne',
        'Neil Gaiman',
        'Niccolo Machiavelli',
        'Norman Mailer',
        'Oscar Levy',
        'Oscar Wilde',
        'P.G. Wodehouse',
        'Paulo Coelho',
        'Peter Carey',
        'Philip Pullman',
        'Philip Roth',
        'Plato',
        'R.L. Stine',
        'Rachel Kushner',
        'Ralph Ellison',
        'Ray Bradbury',
        'Raymond Chandler',
        'Richard Wagner',
        'Richard Wright',
        'Richard Yates',
        'Roald Dahl',
        'Robert Graves',
        'Robert Louis Stevenson',
        'Robert Penn Warren',
        'Rudyard Kipling',
        'Salman Rushdie',
        'Samuel Beckett',
        'Samuel Butler',
        'Samuel Richardson',
        'Saul Bellow',
        'Shivaram Parashuram Bhide',
        'Sir Arthur Conan Doyle',
        'Sir Richard Francis Burton',
        'Stendhal',
        'Stephen Hawking',
        'Stephen King',
        'Sun Tzu',
        'Suzanne Collins',
        'T. Smollett',
        'T.S. Eliot',
        'Theodore Alois Buckley',
        'Theodore Dreiser',
        'Thomas Hardy',
        'Thomas Love Peacock',
        'Thomas Mann',
        'Toni Morrison',
        'Truman Capote',
        'V.S. Naipaul',
        'Vance Packard',
        'Vatsyayana',
        'Victor Hugo',
        'Virgil',
        'Virginia Woolf',
        'Vladimir Nabokov',
        'Voltaire',
        'W.G. Sebald',
        'W.K. Marriott',
        'Walker Percy',
        'Walt Whitman',
        'Walter Scott',
        'Wilhelm Grimm',
        'Wilkie Collins',
        'William Faulkner',
        'William Gibson',
        'William Golding',
        'William Makepeace Thackeray',
        'William Shakespeare',
        'Zadie Smith',
    ];

    protected static array $series = [
        'A Court of Thorns and Roses',
        'A Song of Ice and Fire',
        'Anna Karenina',
        'Bridgerton',
        'Colonel Race',
        'Discworld',
        'Dune',
        'Harry Potter',
        'Hercule Poirot',
        'His Dark Materials',
        'Jane Austen Murder Mysteries',
        'Little Women',
        'Outlander',
        'Percy Jackson',
        'Sherlock Holmes',
        'The Arc of a Scythe',
        'The Bartimaeus Trilogy',
        'The Border Trilogy',
        'The Chronicles of Narnia',
        'The Dark Tower',
        'The Dresden Files',
        'The Eighth Life',
        'The Foundation Series',
        "The Hitchhiker's Guide to the Galaxy",
        'The Hunger Games',
        'The Infinity Cycle',
        'The Inheritance Cycle',
        'The Lord of the Rings',
        'The Maze Runner',
        'The Prison Healer',
        'The Red Rising Saga',
        'The Southern Reach',
        'The Wheel of Time',
        'Thursday Next Series',
        'Twilight',
        'War and Peace',
    ];

    protected static array $titles = [
        '1984',
        '20,000 Leagues Under the Sea',
        'A Bend in the River',
        'A Brief History of Time',
        'A Clockwork Orange',
        'A Confederacy of Dunces',
        "A Doll's House",
        'A Handful of Dust',
        'A Modest Proposal',
        'A Passage to India',
        'A Portrait of the Artist as a Young Man',
        'A Room with a View',
        'A Study in Scarlet',
        'A Tale of Two Cities',
        'A Wrinkle in Time',
        'Absalom, Absalom!',
        'Adventures of Huckleberry Finn',
        "Alice's Adventures in Wonderland",
        'All Quiet on the Western Front',
        "All the King's Men",
        'American Pastoral',
        'An American Tragedy',
        'And Then There Were None',
        'Animal Farm',
        'Anna Karenina',
        'Anne of Green Gables',
        "Are You There God? It's Me, Margaret",
        'As I Lay Dying',
        'Atlas Shrugged',
        'Atonement',
        'Austerlitz',
        'Beloved',
        'Beyond Good and Evil',
        'Bleak House',
        'Blood Meridian',
        'Brave New World',
        'Brideshead Revisited',
        'Candide',
        'Carmilla',
        'Catch-22',
        'Charlie and the Chocolate Factory',
        "Charlotte's Web",
        'Clarissa',
        'Cranford',
        'Crime and Punishment',
        'Dao De Jing: A Minimalist Translation',
        'David Copperfield',
        'Deliverance',
        'Don Quixote',
        'Dora',
        'Dr. Zhivago',
        'Dracula',
        'Dubliners',
        'Dune',
        'East of Eden',
        'Emma',
        'Fahrenheit 451',
        'Faust',
        'For Whom the Bell Tolls',
        'Frankenstein',
        'Freakonomics',
        'Go Tell It on the Mountain',
        'Gone with the Wind',
        'Great Expectations',
        "Grimms' Fairy Tales",
        "Gulliver's Travels",
        'Hamlet',
        "Harry Potter and the Sorcerer's Stone",
        'Heart of Darkness',
        'Herzog',
        'His Dark Materials',
        'Hitting the line',
        'Housekeeping',
        'I, Claudius',
        "If on a Winter's Night a Traveler",
        'In Cold Blood',
        'In Search of Lost Time',
        'Invisible Man',
        'It',
        'Jane Eyre',
        'Josefine Mutzenbacher',
        'Jude the Obscure',
        'L.A. Confidential',
        'Leaves of Grass',
        'Les Miserables',
        'Life of Pi',
        'Little Women',
        'Lolita',
        'Long Walk to Freedom',
        'Lord Jim',
        'Lord of the Flies',
        'Lucky Jim',
        'Madame Bovary',
        'Malone Dies',
        'Meditations',
        'Men Without Women',
        'Metamorphosis',
        'Middlemarch',
        "Midnight's Children",
        'Moby Dick',
        'Money',
        'Mrs. Dalloway',
        'My Bondage and My Freedom',
        'My Life',
        'Native Son',
        'Neuromancer',
        'Never Let Me Go',
        'Nightmare Abbey',
        'Nineteen Eighty Four',
        'Nostromo',
        'Notes from the Underground',
        'Of Mice and Men',
        'Oliver Twist',
        'On the Duty of Civil Disobedience',
        'On the Road',
        "One Flew Over the Cuckoo's Nest",
        'One Hundred Years of Solitude',
        'One Thousand and One Nights',
        'Oscar and Lucinda',
        'Pale Fire',
        'Paradise Lost',
        'Peter Pan',
        "Portnoy's Complaint",
        'Pride and Prejudice',
        'Rabbit, Run',
        'Republic',
        'Revolutionary Road',
        'Robinson Crusoe',
        'Romeo and Juliet',
        'Ruth Fielding in Alaska',
        'Scoop',
        'Second Treatise of Government',
        'Slaughterhouse Five',
        'Stories of Anton Chekhov',
        'Sybil',
        "Tess of the d'Urbervilles",
        'The Adventures of Augie March',
        'The Adventures of Huckleberry Finn',
        'The Adventures of Sherlock Holmes',
        'The Adventures of Tom Sawyer',
        'The Aeneid',
        'The Alchemist',
        'The Ambassadors',
        'The Amber Spyglass',
        'The Art of War',
        'The Big Sleep',
        'The Black Sheep',
        'The Blue Castle',
        'The Brief Wondrous Life of Oscar Wao',
        'The Brothers Karamazov',
        'The Call of the Wild',
        'The Canterbury Tales',
        'The Catcher in the Rye',
        'The Color Purple',
        'The Complete Works of Edgar Allen Poe',
        'The Corrections',
        'The Count of Monte Cristo',
        'The Day of the Locust',
        'The Diary of a Nobody',
        'The Diary of a Young Girl',
        'The Divine Comedy',
        'The Enchanted April',
        'The Fountainhead',
        'The Golden Bowl',
        'The Golden Compass',
        'The Golden Notebook',
        'The Good Soldier',
        'The Grapes of Wrath',
        'The Great Gatsby',
        "The Handmaid's Tale",
        'The Heart is a Lonely Hunter',
        'The Heart of the Matter',
        'The Hobbit',
        'The Hound of the Baskervilles',
        'The Idiot',
        'The Iliad',
        'The King in Yellow',
        'The Kite Runner',
        'The Lion, the Witch, and the Wardrobe',
        'The Little Prince',
        'The Lord of the Rings',
        'The Magic Mountain',
        'The Maltese Falcon',
        'The Master and Margarita',
        'The Moviegoer',
        'The Naked and the Dead',
        'The Odyssey',
        'The Old Man and the Sea',
        'The Pickwick Papers',
        'The Picture of Dorian Gray',
        "The Pilgrim's Progress",
        'The Pillars of the Earth',
        'The Plague',
        'The Portrait of a Lady',
        'The Prime of Miss Jean Brodie',
        'The Prince',
        'The Problems of Philosophy',
        'The Prophet',
        'The Pursuit of Love',
        'The Rainbow',
        'The Red and the Black',
        'The Remains of the Day',
        'The Republic',
        'The Scarlet Letter',
        'The Sleepwalkers',
        'The Sound and the Fury',
        'The Stand',
        'The Strange Case of Dr. Jekyll and Mr. Hyde',
        'The Stranger',
        'The Subtle Knife',
        'The Sun Also Rises',
        'The Testaments',
        'The Thirty-Nine Steps',
        'The Three Musketeers',
        'The Time Machine',
        'The Tin Drum',
        'The Trial',
        'The War of the Worlds',
        'The Waste Land',
        'The Way We Live Now',
        'The Wind in the Willows',
        'The Woman in White',
        'The Wonderful Wizard of Oz',
        'The Works of Edgar Allan Poe',
        'The Yellow Wallpaper',
        'Things Fall Apart',
        'Tinker, Tailor, Soldier, Spy',
        'To Kill a Mockingbird',
        'To the Lighthouse',
        'Tom Jones',
        'Treasure Island',
        'Tristram Shandy',
        'Tropic of Cancer',
        'U.S.A. Trilogy',
        'Ulysses',
        "Uncle Tom's Cabin",
        'Under the Volcano',
        'Underworld',
        'Vanity Fair',
        'Walden',
        'War and Peace',
        'Watchmen',
        'Winnie-the-Pooh',
        'Wuthering Heights',
    ];

    protected static array $genres = [
        'Adventure',
        'Biography',
        'Business',
        "Children's",
        'Classic',
        'Comedy',
        'Comic',
        'Detective',
        'Drama',
        'Fantasy',
        'Graphic Novel',
        'Historical Fiction',
        'Horror',
        'Memoir',
        'Mystery',
        'Mythology',
        'Philosophy',
        'Poetry',
        'Psychology',
        'Religion',
        'Romance',
        'Science Fiction',
        'Thriller',
        'Western',
        'Young Adult',
    ];

    public function author(): string
    {
        return static::randomElement(static::$authors);
    }

    public function genre(): string
    {
        return static::randomElement(static::$genres);
    }

    public function bookTitle(): string
    {
        return static::randomElement(static::$titles);
    }

    public function bookSeries(): string
    {
        return static::randomElement(static::$series);
    }
}
